name: Run Robot Framework + SikuliX Tests

on:
  push:
    branches:
      - main  # Defina a branch que disparará a pipeline

jobs:
  run-tests:
    runs-on: self-hosted  # Use o runner self-hosted configurado na máquina Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Defina a versão do Python que você precisa

    - name: Install dependencies
      run: |
        pip install robotframework
        # Instale as outras dependências necessárias aqui

    - name: Run tests
      run: |
        robot path\to\your\tests
        # Substitua "path\to\your\tests" pelo caminho real para seus testes no formato Windows

