on:
  push:
    branches:
      - Tests_Pipeline_Desktop

jobs:
  automacao-desktop:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Criação do Ambiente Virtual
      run: python -m venv venv
      working-directory: ${EXECDIR}\\resources\\elements  # Substitua pelo caminho correto para o seu projeto

    - name: Ativar Ambiente Virtual
      run: |
        source venv/Scripts/activate  # Para Windows
        # ou use o comando adequado para ativar o ambiente virtual no seu sistema

    - name: Instalar Dependências Python
      run: |
        pip install robotframework
        pip install robotframework-sikulilibrary
        # Adicione outras dependências Python, se necessário

    - name: Executar Automação de Desktop
      run: |
        robot -d ./logs .\tests\meus-testes.robot

    - name: Desativar Ambiente Virtual
      run: deactivate  # Desativa o ambiente virtual

    - name: Publicar Resultados (opcional)
