name: Automação de Desktop

on:
  push:
    branches:
      - Tests_Pipeline_Desktop

jobs:
  automacao-desktop:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Criação do Ambiente Virtual
      run: python -m venv venv
      working-directory: ${EXECDIR}\\resources\\elements

    - name: Ativar Ambiente Virtual
      run: |
        source venv/Scripts/activate
        # ou use o comando adequado para ativar o ambiente virtual no seu sistema

    - name: Instalar Dependências Python
      run: |
        pip install robotframework
        pip install robotframework-sikulilibrary
        # Adicione outras dependências Python, se necessário

    - name: Login no Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Puxar a Imagem Docker
      run: docker pull dilei27/curious:tag

    - name: Executar Automação de Desktop
      run: |
        docker run --rm -v %cd%:/workspace seu-usuario/sua-imagem:tag
      working-directory: /workspace

    - name: Desativar Ambiente Virtual
      run: deactivate

    - name: Publicar Resultados (opcional)
